/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_hh_window_produits (void);
GtkWidget* create_hh_window_supp (void);
GtkWidget* create_hh_window_ajout (void);
GtkWidget* create_hh_window_modif (void);
GtkWidget* create_hh_window_Rechercher (void);
GtkWidget* create_hh_window_rupture (void);
GtkWidget* create_hh_mail (void);
