/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_hh_window_produits (void)
{
  GtkWidget *hh_window_produits;
  GtkWidget *fixed3;
  GtkWidget *hseparator1;
  GtkWidget *hseparator2;
  GtkWidget *treeview2;
  GtkWidget *hh_supprimer;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *label3;
  GtkWidget *hh_ajouter;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label1;
  GtkWidget *hh_modifier;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image2;
  GtkWidget *label2;
  GtkWidget *hh_rechercher;
  GtkWidget *alignment14;
  GtkWidget *hbox14;
  GtkWidget *image16;
  GtkWidget *label14;
  GtkWidget *hh_rupture;
  GtkWidget *alignment15;
  GtkWidget *hbox15;
  GtkWidget *image17;
  GtkWidget *label15;
  GtkWidget *actualiser_prod;
  GtkWidget *alignment23;
  GtkWidget *hbox23;
  GtkWidget *image25;
  GtkWidget *label38;
  GtkWidget *hh_mail;
  GtkWidget *alignment24;
  GtkWidget *hbox24;
  GtkWidget *image26;
  GtkWidget *label40;

  hh_window_produits = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (hh_window_produits), _("PRODUITS"));

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (hh_window_produits), fixed3);

  hseparator1 = gtk_hseparator_new ();
  gtk_widget_show (hseparator1);
  gtk_fixed_put (GTK_FIXED (fixed3), hseparator1, 520, 176);
  gtk_widget_set_size_request (hseparator1, 72, 104);

  hseparator2 = gtk_hseparator_new ();
  gtk_widget_show (hseparator2);
  gtk_fixed_put (GTK_FIXED (fixed3), hseparator2, 184, 176);
  gtk_widget_set_size_request (hseparator2, 16, 16);

  treeview2 = gtk_tree_view_new ();
  gtk_widget_show (treeview2);
  gtk_fixed_put (GTK_FIXED (fixed3), treeview2, 40, 32);
  gtk_widget_set_size_request (treeview2, 984, 584);

  hh_supprimer = gtk_button_new ();
  gtk_widget_show (hh_supprimer);
  gtk_fixed_put (GTK_FIXED (fixed3), hh_supprimer, 816, 736);
  gtk_widget_set_size_request (hh_supprimer, 104, 32);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (hh_supprimer), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image3 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, FALSE, FALSE, 0);

  label3 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label3);
  gtk_box_pack_start (GTK_BOX (hbox3), label3, FALSE, FALSE, 0);

  hh_ajouter = gtk_button_new ();
  gtk_widget_show (hh_ajouter);
  gtk_fixed_put (GTK_FIXED (fixed3), hh_ajouter, 488, 728);
  gtk_widget_set_size_request (hh_ajouter, 88, 32);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (hh_ajouter), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label1 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label1);
  gtk_box_pack_start (GTK_BOX (hbox1), label1, FALSE, FALSE, 0);

  hh_modifier = gtk_button_new ();
  gtk_widget_show (hh_modifier);
  gtk_fixed_put (GTK_FIXED (fixed3), hh_modifier, 144, 728);
  gtk_widget_set_size_request (hh_modifier, 88, 32);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (hh_modifier), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image2 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, FALSE, FALSE, 0);

  label2 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label2);
  gtk_box_pack_start (GTK_BOX (hbox2), label2, FALSE, FALSE, 0);

  hh_rechercher = gtk_button_new ();
  gtk_widget_show (hh_rechercher);
  gtk_fixed_put (GTK_FIXED (fixed3), hh_rechercher, 32, 648);
  gtk_widget_set_size_request (hh_rechercher, 104, 32);

  alignment14 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment14);
  gtk_container_add (GTK_CONTAINER (hh_rechercher), alignment14);

  hbox14 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox14);
  gtk_container_add (GTK_CONTAINER (alignment14), hbox14);

  image16 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image16);
  gtk_box_pack_start (GTK_BOX (hbox14), image16, FALSE, FALSE, 0);

  label14 = gtk_label_new_with_mnemonic (_("Rechercher"));
  gtk_widget_show (label14);
  gtk_box_pack_start (GTK_BOX (hbox14), label14, FALSE, FALSE, 0);

  hh_rupture = gtk_button_new ();
  gtk_widget_show (hh_rupture);
  gtk_fixed_put (GTK_FIXED (fixed3), hh_rupture, 528, 648);
  gtk_widget_set_size_request (hh_rupture, 168, 32);

  alignment15 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment15);
  gtk_container_add (GTK_CONTAINER (hh_rupture), alignment15);

  hbox15 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox15);
  gtk_container_add (GTK_CONTAINER (alignment15), hbox15);

  image17 = gtk_image_new_from_stock ("gtk-dialog-warning", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image17);
  gtk_box_pack_start (GTK_BOX (hbox15), image17, FALSE, FALSE, 0);

  label15 = gtk_label_new_with_mnemonic (_("Produits en rupture"));
  gtk_widget_show (label15);
  gtk_box_pack_start (GTK_BOX (hbox15), label15, FALSE, FALSE, 0);

  actualiser_prod = gtk_button_new ();
  gtk_widget_show (actualiser_prod);
  gtk_fixed_put (GTK_FIXED (fixed3), actualiser_prod, 280, 648);
  gtk_widget_set_size_request (actualiser_prod, 112, 32);

  alignment23 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment23);
  gtk_container_add (GTK_CONTAINER (actualiser_prod), alignment23);

  hbox23 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox23);
  gtk_container_add (GTK_CONTAINER (alignment23), hbox23);

  image25 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image25);
  gtk_box_pack_start (GTK_BOX (hbox23), image25, FALSE, FALSE, 0);

  label38 = gtk_label_new_with_mnemonic (_("Actualiser"));
  gtk_widget_show (label38);
  gtk_box_pack_start (GTK_BOX (hbox23), label38, FALSE, FALSE, 0);

  hh_mail = gtk_button_new ();
  gtk_widget_show (hh_mail);
  gtk_fixed_put (GTK_FIXED (fixed3), hh_mail, 800, 648);
  gtk_widget_set_size_request (hh_mail, 160, 32);

  alignment24 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment24);
  gtk_container_add (GTK_CONTAINER (hh_mail), alignment24);

  hbox24 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox24);
  gtk_container_add (GTK_CONTAINER (alignment24), hbox24);

  image26 = gtk_image_new_from_stock ("gtk-print-preview", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image26);
  gtk_box_pack_start (GTK_BOX (hbox24), image26, FALSE, FALSE, 0);

  label40 = gtk_label_new_with_mnemonic (_("Envoyer un email"));
  gtk_widget_show (label40);
  gtk_box_pack_start (GTK_BOX (hbox24), label40, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) treeview2, "row_activated",
                    G_CALLBACK (on_treeview2_row_activated),
                    NULL);
  g_signal_connect ((gpointer) hh_supprimer, "clicked",
                    G_CALLBACK (on_hh_supprimer_clicked),
                    NULL);
  g_signal_connect ((gpointer) hh_ajouter, "clicked",
                    G_CALLBACK (on_hh_ajouter_clicked),
                    NULL);
  g_signal_connect ((gpointer) hh_modifier, "clicked",
                    G_CALLBACK (on_hh_modifier_clicked),
                    NULL);
  g_signal_connect ((gpointer) hh_rechercher, "clicked",
                    G_CALLBACK (on_hh_rechercher_clicked),
                    NULL);
  g_signal_connect ((gpointer) hh_rupture, "clicked",
                    G_CALLBACK (on_hh_rupture_clicked),
                    NULL);
  g_signal_connect ((gpointer) actualiser_prod, "clicked",
                    G_CALLBACK (on_actualiser_prod_clicked),
                    NULL);
  g_signal_connect ((gpointer) hh_mail, "clicked",
                    G_CALLBACK (on_hh_mail_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (hh_window_produits, hh_window_produits, "hh_window_produits");
  GLADE_HOOKUP_OBJECT (hh_window_produits, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (hh_window_produits, hseparator1, "hseparator1");
  GLADE_HOOKUP_OBJECT (hh_window_produits, hseparator2, "hseparator2");
  GLADE_HOOKUP_OBJECT (hh_window_produits, treeview2, "treeview2");
  GLADE_HOOKUP_OBJECT (hh_window_produits, hh_supprimer, "hh_supprimer");
  GLADE_HOOKUP_OBJECT (hh_window_produits, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (hh_window_produits, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (hh_window_produits, image3, "image3");
  GLADE_HOOKUP_OBJECT (hh_window_produits, label3, "label3");
  GLADE_HOOKUP_OBJECT (hh_window_produits, hh_ajouter, "hh_ajouter");
  GLADE_HOOKUP_OBJECT (hh_window_produits, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (hh_window_produits, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (hh_window_produits, image1, "image1");
  GLADE_HOOKUP_OBJECT (hh_window_produits, label1, "label1");
  GLADE_HOOKUP_OBJECT (hh_window_produits, hh_modifier, "hh_modifier");
  GLADE_HOOKUP_OBJECT (hh_window_produits, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (hh_window_produits, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (hh_window_produits, image2, "image2");
  GLADE_HOOKUP_OBJECT (hh_window_produits, label2, "label2");
  GLADE_HOOKUP_OBJECT (hh_window_produits, hh_rechercher, "hh_rechercher");
  GLADE_HOOKUP_OBJECT (hh_window_produits, alignment14, "alignment14");
  GLADE_HOOKUP_OBJECT (hh_window_produits, hbox14, "hbox14");
  GLADE_HOOKUP_OBJECT (hh_window_produits, image16, "image16");
  GLADE_HOOKUP_OBJECT (hh_window_produits, label14, "label14");
  GLADE_HOOKUP_OBJECT (hh_window_produits, hh_rupture, "hh_rupture");
  GLADE_HOOKUP_OBJECT (hh_window_produits, alignment15, "alignment15");
  GLADE_HOOKUP_OBJECT (hh_window_produits, hbox15, "hbox15");
  GLADE_HOOKUP_OBJECT (hh_window_produits, image17, "image17");
  GLADE_HOOKUP_OBJECT (hh_window_produits, label15, "label15");
  GLADE_HOOKUP_OBJECT (hh_window_produits, actualiser_prod, "actualiser_prod");
  GLADE_HOOKUP_OBJECT (hh_window_produits, alignment23, "alignment23");
  GLADE_HOOKUP_OBJECT (hh_window_produits, hbox23, "hbox23");
  GLADE_HOOKUP_OBJECT (hh_window_produits, image25, "image25");
  GLADE_HOOKUP_OBJECT (hh_window_produits, label38, "label38");
  GLADE_HOOKUP_OBJECT (hh_window_produits, hh_mail, "hh_mail");
  GLADE_HOOKUP_OBJECT (hh_window_produits, alignment24, "alignment24");
  GLADE_HOOKUP_OBJECT (hh_window_produits, hbox24, "hbox24");
  GLADE_HOOKUP_OBJECT (hh_window_produits, image26, "image26");
  GLADE_HOOKUP_OBJECT (hh_window_produits, label40, "label40");

  return hh_window_produits;
}

GtkWidget*
create_hh_window_supp (void)
{
  GtkWidget *hh_window_supp;
  GtkWidget *fixed4;
  GtkWidget *id_conf_supp;
  GtkWidget *label37;
  GtkWidget *errror;
  GtkWidget *msg_supp;
  GtkWidget *hh_supp_oui;
  GtkWidget *hh_supp_valider;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image6;
  GtkWidget *label6;
  GtkWidget *affich_supp;
  GtkWidget *alignment22;
  GtkWidget *hbox22;
  GtkWidget *image24;
  GtkWidget *label35;
  GtkWidget *label36;

  hh_window_supp = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (hh_window_supp), _("SUPPRIMER"));

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (hh_window_supp), fixed4);

  id_conf_supp = gtk_entry_new ();
  gtk_widget_show (id_conf_supp);
  gtk_fixed_put (GTK_FIXED (fixed4), id_conf_supp, 40, 64);
  gtk_widget_set_size_request (id_conf_supp, 160, 27);
  gtk_editable_set_editable (GTK_EDITABLE (id_conf_supp), FALSE);
  gtk_entry_set_invisible_char (GTK_ENTRY (id_conf_supp), 8226);

  label37 = gtk_label_new (_("ID :"));
  gtk_widget_show (label37);
  gtk_fixed_put (GTK_FIXED (fixed4), label37, 0, 64);
  gtk_widget_set_size_request (label37, 56, 25);

  errror = gtk_label_new ("");
  gtk_widget_show (errror);
  gtk_fixed_put (GTK_FIXED (fixed4), errror, 208, 56);
  gtk_widget_set_size_request (errror, 320, 40);

  msg_supp = gtk_label_new (_("etes vous sur de supprimer cet \303\251l\303\251ment ?"));
  gtk_widget_show (msg_supp);
  gtk_fixed_put (GTK_FIXED (fixed4), msg_supp, 128, 104);
  gtk_widget_set_size_request (msg_supp, 288, 40);
  gtk_label_set_justify (GTK_LABEL (msg_supp), GTK_JUSTIFY_CENTER);

  hh_supp_oui = gtk_check_button_new_with_mnemonic (_("oui"));
  gtk_widget_show (hh_supp_oui);
  gtk_fixed_put (GTK_FIXED (fixed4), hh_supp_oui, 160, 168);
  gtk_widget_set_size_request (hh_supp_oui, 64, 32);

  hh_supp_valider = gtk_button_new ();
  gtk_widget_show (hh_supp_valider);
  gtk_fixed_put (GTK_FIXED (fixed4), hh_supp_valider, 328, 168);
  gtk_widget_set_size_request (hh_supp_valider, 80, 32);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (hh_supp_valider), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image6 = gtk_image_new_from_stock ("gtk-yes", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox6), image6, FALSE, FALSE, 0);

  label6 = gtk_label_new_with_mnemonic (_("valider"));
  gtk_widget_show (label6);
  gtk_box_pack_start (GTK_BOX (hbox6), label6, FALSE, FALSE, 0);

  affich_supp = gtk_button_new ();
  gtk_widget_show (affich_supp);
  gtk_fixed_put (GTK_FIXED (fixed4), affich_supp, 232, 224);
  gtk_widget_set_size_request (affich_supp, 88, 32);

  alignment22 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment22);
  gtk_container_add (GTK_CONTAINER (affich_supp), alignment22);

  hbox22 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox22);
  gtk_container_add (GTK_CONTAINER (alignment22), hbox22);

  image24 = gtk_image_new_from_stock ("gtk-about", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image24);
  gtk_box_pack_start (GTK_BOX (hbox22), image24, FALSE, FALSE, 0);

  label35 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label35);
  gtk_box_pack_start (GTK_BOX (hbox22), label35, FALSE, FALSE, 0);

  label36 = gtk_label_new (_("Merci de confirmer "));
  gtk_widget_show (label36);
  gtk_fixed_put (GTK_FIXED (fixed4), label36, 144, 24);
  gtk_widget_set_size_request (label36, 240, 16);

  g_signal_connect ((gpointer) hh_supp_oui, "toggled",
                    G_CALLBACK (on_hh_supp_oui_toggled),
                    NULL);
  g_signal_connect ((gpointer) hh_supp_valider, "clicked",
                    G_CALLBACK (on_hh_supp_valider_clicked),
                    NULL);
  g_signal_connect ((gpointer) affich_supp, "clicked",
                    G_CALLBACK (on_affich_supp_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (hh_window_supp, hh_window_supp, "hh_window_supp");
  GLADE_HOOKUP_OBJECT (hh_window_supp, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (hh_window_supp, id_conf_supp, "id_conf_supp");
  GLADE_HOOKUP_OBJECT (hh_window_supp, label37, "label37");
  GLADE_HOOKUP_OBJECT (hh_window_supp, errror, "errror");
  GLADE_HOOKUP_OBJECT (hh_window_supp, msg_supp, "msg_supp");
  GLADE_HOOKUP_OBJECT (hh_window_supp, hh_supp_oui, "hh_supp_oui");
  GLADE_HOOKUP_OBJECT (hh_window_supp, hh_supp_valider, "hh_supp_valider");
  GLADE_HOOKUP_OBJECT (hh_window_supp, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (hh_window_supp, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (hh_window_supp, image6, "image6");
  GLADE_HOOKUP_OBJECT (hh_window_supp, label6, "label6");
  GLADE_HOOKUP_OBJECT (hh_window_supp, affich_supp, "affich_supp");
  GLADE_HOOKUP_OBJECT (hh_window_supp, alignment22, "alignment22");
  GLADE_HOOKUP_OBJECT (hh_window_supp, hbox22, "hbox22");
  GLADE_HOOKUP_OBJECT (hh_window_supp, image24, "image24");
  GLADE_HOOKUP_OBJECT (hh_window_supp, label35, "label35");
  GLADE_HOOKUP_OBJECT (hh_window_supp, label36, "label36");

  return hh_window_supp;
}

GtkWidget*
create_hh_window_ajout (void)
{
  GtkWidget *hh_window_ajout;
  GtkWidget *fixed5;
  GtkWidget *hh_nom_ajout;
  GtkWidget *hh_quantite_ajout;
  GtkObject *hh_j_ajouter_adj;
  GtkWidget *hh_j_ajouter;
  GtkObject *hh_m_ajouter_adj;
  GtkWidget *hh_m_ajouter;
  GtkObject *hh_a_ajouter_adj;
  GtkWidget *hh_a_ajouter;
  GtkObject *spinbutton7_adj;
  GtkWidget *spinbutton7;
  GtkWidget *date_expiration;
  GtkObject *hh_m_exp_adj;
  GtkWidget *hh_m_exp;
  GtkObject *hh_a_exp_adj;
  GtkWidget *hh_a_exp;
  GtkWidget *quantitea;
  GtkWidget *hh_id_ajout;
  GtkWidget *datea;
  GtkWidget *nom_proda;
  GtkWidget *id;
  GtkWidget *type;
  GtkWidget *fruit_a;
  GSList *fruit_a_group = NULL;
  GtkWidget *legume_a;
  GtkWidget *viande_a;
  GtkWidget *liquides_a;
  GtkWidget *ingredients_a;
  GtkWidget *hh_ajout_prod;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image4;
  GtkWidget *label4;
  GtkWidget *hh_annuler_ajout;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image5;
  GtkWidget *label5;
  GtkWidget *affich_ajout;
  GtkWidget *alignment18;
  GtkWidget *hbox18;
  GtkWidget *image20;
  GtkWidget *label25;
  GtkWidget *ajout_err;

  hh_window_ajout = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (hh_window_ajout), _("AJOUTER"));

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (hh_window_ajout), fixed5);

  hh_nom_ajout = gtk_entry_new ();
  gtk_widget_show (hh_nom_ajout);
  gtk_fixed_put (GTK_FIXED (fixed5), hh_nom_ajout, 160, 112);
  gtk_widget_set_size_request (hh_nom_ajout, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (hh_nom_ajout), 8226);

  hh_quantite_ajout = gtk_entry_new ();
  gtk_widget_show (hh_quantite_ajout);
  gtk_fixed_put (GTK_FIXED (fixed5), hh_quantite_ajout, 160, 192);
  gtk_widget_set_size_request (hh_quantite_ajout, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (hh_quantite_ajout), 8226);

  hh_j_ajouter_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  hh_j_ajouter = gtk_spin_button_new (GTK_ADJUSTMENT (hh_j_ajouter_adj), 1, 0);
  gtk_widget_show (hh_j_ajouter);
  gtk_fixed_put (GTK_FIXED (fixed5), hh_j_ajouter, 144, 232);
  gtk_widget_set_size_request (hh_j_ajouter, 60, 27);

  hh_m_ajouter_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  hh_m_ajouter = gtk_spin_button_new (GTK_ADJUSTMENT (hh_m_ajouter_adj), 1, 0);
  gtk_widget_show (hh_m_ajouter);
  gtk_fixed_put (GTK_FIXED (fixed5), hh_m_ajouter, 216, 232);
  gtk_widget_set_size_request (hh_m_ajouter, 60, 27);

  hh_a_ajouter_adj = gtk_adjustment_new (2021, 2021, 2025, 1, 10, 10);
  hh_a_ajouter = gtk_spin_button_new (GTK_ADJUSTMENT (hh_a_ajouter_adj), 1, 0);
  gtk_widget_show (hh_a_ajouter);
  gtk_fixed_put (GTK_FIXED (fixed5), hh_a_ajouter, 288, 232);
  gtk_widget_set_size_request (hh_a_ajouter, 64, 24);

  spinbutton7_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbutton7 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton7_adj), 1, 0);
  gtk_widget_show (spinbutton7);
  gtk_fixed_put (GTK_FIXED (fixed5), spinbutton7, 144, 272);
  gtk_widget_set_size_request (spinbutton7, 60, 27);

  date_expiration = gtk_label_new (_("Dade d'expiration :"));
  gtk_widget_show (date_expiration);
  gtk_fixed_put (GTK_FIXED (fixed5), date_expiration, 0, 272);
  gtk_widget_set_size_request (date_expiration, 144, 32);

  hh_m_exp_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  hh_m_exp = gtk_spin_button_new (GTK_ADJUSTMENT (hh_m_exp_adj), 1, 0);
  gtk_widget_show (hh_m_exp);
  gtk_fixed_put (GTK_FIXED (fixed5), hh_m_exp, 216, 272);
  gtk_widget_set_size_request (hh_m_exp, 60, 27);

  hh_a_exp_adj = gtk_adjustment_new (2021, 2021, 2025, 1, 10, 10);
  hh_a_exp = gtk_spin_button_new (GTK_ADJUSTMENT (hh_a_exp_adj), 1, 0);
  gtk_widget_show (hh_a_exp);
  gtk_fixed_put (GTK_FIXED (fixed5), hh_a_exp, 288, 272);
  gtk_widget_set_size_request (hh_a_exp, 60, 27);

  quantitea = gtk_label_new (_("Quantit\303\251 :"));
  gtk_widget_show (quantitea);
  gtk_fixed_put (GTK_FIXED (fixed5), quantitea, 56, 192);
  gtk_widget_set_size_request (quantitea, 96, 32);

  hh_id_ajout = gtk_entry_new ();
  gtk_widget_show (hh_id_ajout);
  gtk_fixed_put (GTK_FIXED (fixed5), hh_id_ajout, 160, 152);
  gtk_widget_set_size_request (hh_id_ajout, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (hh_id_ajout), 8226);

  datea = gtk_label_new (_("Date d'ajout :"));
  gtk_widget_show (datea);
  gtk_fixed_put (GTK_FIXED (fixed5), datea, 40, 232);
  gtk_widget_set_size_request (datea, 96, 24);

  nom_proda = gtk_label_new (_("Nom du produit :"));
  gtk_widget_show (nom_proda);
  gtk_fixed_put (GTK_FIXED (fixed5), nom_proda, 16, 112);
  gtk_widget_set_size_request (nom_proda, 128, 32);

  id = gtk_label_new (_("ID du produit :"));
  gtk_widget_show (id);
  gtk_fixed_put (GTK_FIXED (fixed5), id, 32, 160);
  gtk_widget_set_size_request (id, 120, 16);

  type = gtk_label_new (_("Type :"));
  gtk_widget_show (type);
  gtk_fixed_put (GTK_FIXED (fixed5), type, 16, 64);
  gtk_widget_set_size_request (type, 48, 16);

  fruit_a = gtk_radio_button_new_with_mnemonic (NULL, _("Fruit"));
  gtk_widget_show (fruit_a);
  gtk_fixed_put (GTK_FIXED (fixed5), fruit_a, 88, 16);
  gtk_widget_set_size_request (fruit_a, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (fruit_a), fruit_a_group);
  fruit_a_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (fruit_a));

  legume_a = gtk_radio_button_new_with_mnemonic (NULL, _("Legume"));
  gtk_widget_show (legume_a);
  gtk_fixed_put (GTK_FIXED (fixed5), legume_a, 88, 48);
  gtk_widget_set_size_request (legume_a, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (legume_a), fruit_a_group);
  fruit_a_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (legume_a));

  viande_a = gtk_radio_button_new_with_mnemonic (NULL, _("Viande"));
  gtk_widget_show (viande_a);
  gtk_fixed_put (GTK_FIXED (fixed5), viande_a, 88, 80);
  gtk_widget_set_size_request (viande_a, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (viande_a), fruit_a_group);
  fruit_a_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (viande_a));

  liquides_a = gtk_radio_button_new_with_mnemonic (NULL, _("Liquides"));
  gtk_widget_show (liquides_a);
  gtk_fixed_put (GTK_FIXED (fixed5), liquides_a, 240, 24);
  gtk_widget_set_size_request (liquides_a, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (liquides_a), fruit_a_group);
  fruit_a_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (liquides_a));

  ingredients_a = gtk_radio_button_new_with_mnemonic (NULL, _("Ingr\303\251dients"));
  gtk_widget_show (ingredients_a);
  gtk_fixed_put (GTK_FIXED (fixed5), ingredients_a, 240, 64);
  gtk_widget_set_size_request (ingredients_a, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (ingredients_a), fruit_a_group);
  fruit_a_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (ingredients_a));

  hh_ajout_prod = gtk_button_new ();
  gtk_widget_show (hh_ajout_prod);
  gtk_fixed_put (GTK_FIXED (fixed5), hh_ajout_prod, 32, 384);
  gtk_widget_set_size_request (hh_ajout_prod, 80, 32);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (hh_ajout_prod), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image4 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox4), image4, FALSE, FALSE, 0);

  label4 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label4);
  gtk_box_pack_start (GTK_BOX (hbox4), label4, FALSE, FALSE, 0);

  hh_annuler_ajout = gtk_button_new ();
  gtk_widget_show (hh_annuler_ajout);
  gtk_fixed_put (GTK_FIXED (fixed5), hh_annuler_ajout, 152, 384);
  gtk_widget_set_size_request (hh_annuler_ajout, 88, 32);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (hh_annuler_ajout), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image5 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox5), image5, FALSE, FALSE, 0);

  label5 = gtk_label_new_with_mnemonic (_("Annuler"));
  gtk_widget_show (label5);
  gtk_box_pack_start (GTK_BOX (hbox5), label5, FALSE, FALSE, 0);

  affich_ajout = gtk_button_new ();
  gtk_widget_show (affich_ajout);
  gtk_fixed_put (GTK_FIXED (fixed5), affich_ajout, 272, 384);
  gtk_widget_set_size_request (affich_ajout, 88, 32);

  alignment18 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment18);
  gtk_container_add (GTK_CONTAINER (affich_ajout), alignment18);

  hbox18 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox18);
  gtk_container_add (GTK_CONTAINER (alignment18), hbox18);

  image20 = gtk_image_new_from_stock ("gtk-about", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image20);
  gtk_box_pack_start (GTK_BOX (hbox18), image20, FALSE, FALSE, 0);

  label25 = gtk_label_new_with_mnemonic (_("Afficher"));
  gtk_widget_show (label25);
  gtk_box_pack_start (GTK_BOX (hbox18), label25, FALSE, FALSE, 0);

  ajout_err = gtk_label_new ("");
  gtk_widget_show (ajout_err);
  gtk_fixed_put (GTK_FIXED (fixed5), ajout_err, 40, 328);
  gtk_widget_set_size_request (ajout_err, 296, 24);

  g_signal_connect ((gpointer) fruit_a, "toggled",
                    G_CALLBACK (on_fruit_a_toggled),
                    NULL);
  g_signal_connect ((gpointer) legume_a, "toggled",
                    G_CALLBACK (on_legume_a_toggled),
                    NULL);
  g_signal_connect ((gpointer) viande_a, "toggled",
                    G_CALLBACK (on_viande_a_toggled),
                    NULL);
  g_signal_connect ((gpointer) liquides_a, "toggled",
                    G_CALLBACK (on_liquides_a_toggled),
                    NULL);
  g_signal_connect ((gpointer) ingredients_a, "toggled",
                    G_CALLBACK (on_ingredients_a_toggled),
                    NULL);
  g_signal_connect ((gpointer) hh_ajout_prod, "clicked",
                    G_CALLBACK (on_hh_ajout_prod_clicked),
                    NULL);
  g_signal_connect ((gpointer) hh_annuler_ajout, "clicked",
                    G_CALLBACK (on_hh_annuler_ajout_clicked),
                    NULL);
  g_signal_connect ((gpointer) affich_ajout, "clicked",
                    G_CALLBACK (on_affich_ajout_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (hh_window_ajout, hh_window_ajout, "hh_window_ajout");
  GLADE_HOOKUP_OBJECT (hh_window_ajout, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (hh_window_ajout, hh_nom_ajout, "hh_nom_ajout");
  GLADE_HOOKUP_OBJECT (hh_window_ajout, hh_quantite_ajout, "hh_quantite_ajout");
  GLADE_HOOKUP_OBJECT (hh_window_ajout, hh_j_ajouter, "hh_j_ajouter");
  GLADE_HOOKUP_OBJECT (hh_window_ajout, hh_m_ajouter, "hh_m_ajouter");
  GLADE_HOOKUP_OBJECT (hh_window_ajout, hh_a_ajouter, "hh_a_ajouter");
  GLADE_HOOKUP_OBJECT (hh_window_ajout, spinbutton7, "spinbutton7");
  GLADE_HOOKUP_OBJECT (hh_window_ajout, date_expiration, "date_expiration");
  GLADE_HOOKUP_OBJECT (hh_window_ajout, hh_m_exp, "hh_m_exp");
  GLADE_HOOKUP_OBJECT (hh_window_ajout, hh_a_exp, "hh_a_exp");
  GLADE_HOOKUP_OBJECT (hh_window_ajout, quantitea, "quantitea");
  GLADE_HOOKUP_OBJECT (hh_window_ajout, hh_id_ajout, "hh_id_ajout");
  GLADE_HOOKUP_OBJECT (hh_window_ajout, datea, "datea");
  GLADE_HOOKUP_OBJECT (hh_window_ajout, nom_proda, "nom_proda");
  GLADE_HOOKUP_OBJECT (hh_window_ajout, id, "id");
  GLADE_HOOKUP_OBJECT (hh_window_ajout, type, "type");
  GLADE_HOOKUP_OBJECT (hh_window_ajout, fruit_a, "fruit_a");
  GLADE_HOOKUP_OBJECT (hh_window_ajout, legume_a, "legume_a");
  GLADE_HOOKUP_OBJECT (hh_window_ajout, viande_a, "viande_a");
  GLADE_HOOKUP_OBJECT (hh_window_ajout, liquides_a, "liquides_a");
  GLADE_HOOKUP_OBJECT (hh_window_ajout, ingredients_a, "ingredients_a");
  GLADE_HOOKUP_OBJECT (hh_window_ajout, hh_ajout_prod, "hh_ajout_prod");
  GLADE_HOOKUP_OBJECT (hh_window_ajout, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (hh_window_ajout, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (hh_window_ajout, image4, "image4");
  GLADE_HOOKUP_OBJECT (hh_window_ajout, label4, "label4");
  GLADE_HOOKUP_OBJECT (hh_window_ajout, hh_annuler_ajout, "hh_annuler_ajout");
  GLADE_HOOKUP_OBJECT (hh_window_ajout, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (hh_window_ajout, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (hh_window_ajout, image5, "image5");
  GLADE_HOOKUP_OBJECT (hh_window_ajout, label5, "label5");
  GLADE_HOOKUP_OBJECT (hh_window_ajout, affich_ajout, "affich_ajout");
  GLADE_HOOKUP_OBJECT (hh_window_ajout, alignment18, "alignment18");
  GLADE_HOOKUP_OBJECT (hh_window_ajout, hbox18, "hbox18");
  GLADE_HOOKUP_OBJECT (hh_window_ajout, image20, "image20");
  GLADE_HOOKUP_OBJECT (hh_window_ajout, label25, "label25");
  GLADE_HOOKUP_OBJECT (hh_window_ajout, ajout_err, "ajout_err");

  return hh_window_ajout;
}

GtkWidget*
create_hh_window_modif (void)
{
  GtkWidget *hh_window_modif;
  GtkWidget *fixed6;
  GtkObject *hh_j_exp_mod_adj;
  GtkWidget *hh_j_exp_mod;
  GtkObject *hh_m_exp_mod_adj;
  GtkWidget *hh_m_exp_mod;
  GtkObject *hh_a_exp_mod_adj;
  GtkWidget *hh_a_exp_mod;
  GtkWidget *hh_nom_modifier;
  GtkWidget *annuler_modif;
  GtkWidget *alignment7;
  GtkWidget *hbox7;
  GtkWidget *image7;
  GtkWidget *label7;
  GtkWidget *hh_quantite_modifier;
  GtkWidget *hh_id_modifier;
  GtkObject *hh_j_ajouter_mod_adj;
  GtkWidget *hh_j_ajouter_mod;
  GtkObject *hh_m_ajouter_mod_adj;
  GtkWidget *hh_m_ajouter_mod;
  GtkObject *hh_a_ajouter_mod_adj;
  GtkWidget *hh_a_ajouter_mod;
  GtkWidget *affich_modif;
  GtkWidget *alignment16;
  GtkWidget *hbox16;
  GtkWidget *image18;
  GtkWidget *label23;
  GtkWidget *id_modif;
  GtkWidget *date_exp;
  GtkWidget *date_a_modif;
  GtkWidget *quantitea;
  GtkWidget *type_modifier;
  GtkWidget *nom_modifier;
  GtkWidget *type_m;
  GtkWidget *label34;
  GtkWidget *modif;

  hh_window_modif = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (hh_window_modif), _("MODIFIER"));

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_container_add (GTK_CONTAINER (hh_window_modif), fixed6);

  hh_j_exp_mod_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  hh_j_exp_mod = gtk_spin_button_new (GTK_ADJUSTMENT (hh_j_exp_mod_adj), 1, 0);
  gtk_widget_show (hh_j_exp_mod);
  gtk_fixed_put (GTK_FIXED (fixed6), hh_j_exp_mod, 144, 344);
  gtk_widget_set_size_request (hh_j_exp_mod, 56, 24);

  hh_m_exp_mod_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  hh_m_exp_mod = gtk_spin_button_new (GTK_ADJUSTMENT (hh_m_exp_mod_adj), 1, 0);
  gtk_widget_show (hh_m_exp_mod);
  gtk_fixed_put (GTK_FIXED (fixed6), hh_m_exp_mod, 208, 344);
  gtk_widget_set_size_request (hh_m_exp_mod, 56, 24);

  hh_a_exp_mod_adj = gtk_adjustment_new (2021, 2021, 2025, 1, 10, 10);
  hh_a_exp_mod = gtk_spin_button_new (GTK_ADJUSTMENT (hh_a_exp_mod_adj), 1, 0);
  gtk_widget_show (hh_a_exp_mod);
  gtk_fixed_put (GTK_FIXED (fixed6), hh_a_exp_mod, 272, 344);
  gtk_widget_set_size_request (hh_a_exp_mod, 64, 24);

  hh_nom_modifier = gtk_entry_new ();
  gtk_widget_show (hh_nom_modifier);
  gtk_fixed_put (GTK_FIXED (fixed6), hh_nom_modifier, 144, 120);
  gtk_widget_set_size_request (hh_nom_modifier, 160, 27);
  gtk_editable_set_editable (GTK_EDITABLE (hh_nom_modifier), FALSE);
  gtk_entry_set_invisible_char (GTK_ENTRY (hh_nom_modifier), 8226);

  annuler_modif = gtk_button_new ();
  gtk_widget_show (annuler_modif);
  gtk_fixed_put (GTK_FIXED (fixed6), annuler_modif, 144, 432);
  gtk_widget_set_size_request (annuler_modif, 82, 32);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (annuler_modif), alignment7);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox7);

  image7 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox7), image7, FALSE, FALSE, 0);

  label7 = gtk_label_new_with_mnemonic (_("Annuler"));
  gtk_widget_show (label7);
  gtk_box_pack_start (GTK_BOX (hbox7), label7, FALSE, FALSE, 0);

  hh_quantite_modifier = gtk_entry_new ();
  gtk_widget_show (hh_quantite_modifier);
  gtk_fixed_put (GTK_FIXED (fixed6), hh_quantite_modifier, 144, 232);
  gtk_widget_set_size_request (hh_quantite_modifier, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (hh_quantite_modifier), 8226);

  hh_id_modifier = gtk_entry_new ();
  gtk_widget_show (hh_id_modifier);
  gtk_fixed_put (GTK_FIXED (fixed6), hh_id_modifier, 144, 176);
  gtk_widget_set_size_request (hh_id_modifier, 160, 27);
  gtk_editable_set_editable (GTK_EDITABLE (hh_id_modifier), FALSE);
  gtk_entry_set_invisible_char (GTK_ENTRY (hh_id_modifier), 8226);

  hh_j_ajouter_mod_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  hh_j_ajouter_mod = gtk_spin_button_new (GTK_ADJUSTMENT (hh_j_ajouter_mod_adj), 1, 0);
  gtk_widget_show (hh_j_ajouter_mod);
  gtk_fixed_put (GTK_FIXED (fixed6), hh_j_ajouter_mod, 144, 288);
  gtk_widget_set_size_request (hh_j_ajouter_mod, 60, 27);

  hh_m_ajouter_mod_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  hh_m_ajouter_mod = gtk_spin_button_new (GTK_ADJUSTMENT (hh_m_ajouter_mod_adj), 1, 0);
  gtk_widget_show (hh_m_ajouter_mod);
  gtk_fixed_put (GTK_FIXED (fixed6), hh_m_ajouter_mod, 208, 288);
  gtk_widget_set_size_request (hh_m_ajouter_mod, 60, 27);

  hh_a_ajouter_mod_adj = gtk_adjustment_new (2021, 2021, 2025, 1, 10, 10);
  hh_a_ajouter_mod = gtk_spin_button_new (GTK_ADJUSTMENT (hh_a_ajouter_mod_adj), 1, 0);
  gtk_widget_show (hh_a_ajouter_mod);
  gtk_fixed_put (GTK_FIXED (fixed6), hh_a_ajouter_mod, 272, 288);
  gtk_widget_set_size_request (hh_a_ajouter_mod, 64, 24);

  affich_modif = gtk_button_new ();
  gtk_widget_show (affich_modif);
  gtk_fixed_put (GTK_FIXED (fixed6), affich_modif, 264, 432);
  gtk_widget_set_size_request (affich_modif, 88, 32);

  alignment16 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment16);
  gtk_container_add (GTK_CONTAINER (affich_modif), alignment16);

  hbox16 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox16);
  gtk_container_add (GTK_CONTAINER (alignment16), hbox16);

  image18 = gtk_image_new_from_stock ("gtk-about", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image18);
  gtk_box_pack_start (GTK_BOX (hbox16), image18, FALSE, FALSE, 0);

  label23 = gtk_label_new_with_mnemonic (_("Afficher"));
  gtk_widget_show (label23);
  gtk_box_pack_start (GTK_BOX (hbox16), label23, FALSE, FALSE, 0);

  id_modif = gtk_label_new (_("ID du produit :"));
  gtk_widget_show (id_modif);
  gtk_fixed_put (GTK_FIXED (fixed6), id_modif, 24, 184);
  gtk_widget_set_size_request (id_modif, 112, 16);

  date_exp = gtk_label_new (_("Date d'expiration :"));
  gtk_widget_show (date_exp);
  gtk_fixed_put (GTK_FIXED (fixed6), date_exp, 8, 344);
  gtk_widget_set_size_request (date_exp, 128, 24);

  date_a_modif = gtk_label_new (_("Date d'ajout :"));
  gtk_widget_show (date_a_modif);
  gtk_fixed_put (GTK_FIXED (fixed6), date_a_modif, 32, 296);
  gtk_widget_set_size_request (date_a_modif, 104, 16);

  quantitea = gtk_label_new (_("Quantit\303\251 :"));
  gtk_widget_show (quantitea);
  gtk_fixed_put (GTK_FIXED (fixed6), quantitea, 56, 232);
  gtk_widget_set_size_request (quantitea, 80, 24);

  type_modifier = gtk_label_new (_("Type :"));
  gtk_widget_show (type_modifier);
  gtk_fixed_put (GTK_FIXED (fixed6), type_modifier, 64, 64);
  gtk_widget_set_size_request (type_modifier, 80, 24);

  nom_modifier = gtk_label_new (_("Nom du produit :"));
  gtk_widget_show (nom_modifier);
  gtk_fixed_put (GTK_FIXED (fixed6), nom_modifier, 0, 120);
  gtk_widget_set_size_request (nom_modifier, 136, 24);

  type_m = gtk_combo_box_entry_new_text ();
  gtk_widget_show (type_m);
  gtk_fixed_put (GTK_FIXED (fixed6), type_m, 144, 64);
  gtk_widget_set_size_request (type_m, 165, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (type_m), _("Fruit"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (type_m), _("Legume"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (type_m), _("Viande"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (type_m), _("Liquides"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (type_m), _("Ingedients"));

  label34 = gtk_label_new ("");
  gtk_widget_show (label34);
  gtk_fixed_put (GTK_FIXED (fixed6), label34, 48, 496);
  gtk_widget_set_size_request (label34, 256, 40);

  modif = gtk_button_new_with_mnemonic ("modifier");
  gtk_widget_show (modif);
  gtk_fixed_put (GTK_FIXED (fixed6), modif, 32, 432);
  gtk_widget_set_size_request (modif, 80, 32);

  g_signal_connect ((gpointer) annuler_modif, "clicked",
                    G_CALLBACK (on_annuler_modif_clicked),
                    NULL);
  g_signal_connect ((gpointer) affich_modif, "clicked",
                    G_CALLBACK (on_affich_modif_clicked),
                    NULL);
  g_signal_connect ((gpointer) modif, "clicked",
                    G_CALLBACK (on_modif_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (hh_window_modif, hh_window_modif, "hh_window_modif");
  GLADE_HOOKUP_OBJECT (hh_window_modif, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (hh_window_modif, hh_j_exp_mod, "hh_j_exp_mod");
  GLADE_HOOKUP_OBJECT (hh_window_modif, hh_m_exp_mod, "hh_m_exp_mod");
  GLADE_HOOKUP_OBJECT (hh_window_modif, hh_a_exp_mod, "hh_a_exp_mod");
  GLADE_HOOKUP_OBJECT (hh_window_modif, hh_nom_modifier, "hh_nom_modifier");
  GLADE_HOOKUP_OBJECT (hh_window_modif, annuler_modif, "annuler_modif");
  GLADE_HOOKUP_OBJECT (hh_window_modif, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (hh_window_modif, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (hh_window_modif, image7, "image7");
  GLADE_HOOKUP_OBJECT (hh_window_modif, label7, "label7");
  GLADE_HOOKUP_OBJECT (hh_window_modif, hh_quantite_modifier, "hh_quantite_modifier");
  GLADE_HOOKUP_OBJECT (hh_window_modif, hh_id_modifier, "hh_id_modifier");
  GLADE_HOOKUP_OBJECT (hh_window_modif, hh_j_ajouter_mod, "hh_j_ajouter_mod");
  GLADE_HOOKUP_OBJECT (hh_window_modif, hh_m_ajouter_mod, "hh_m_ajouter_mod");
  GLADE_HOOKUP_OBJECT (hh_window_modif, hh_a_ajouter_mod, "hh_a_ajouter_mod");
  GLADE_HOOKUP_OBJECT (hh_window_modif, affich_modif, "affich_modif");
  GLADE_HOOKUP_OBJECT (hh_window_modif, alignment16, "alignment16");
  GLADE_HOOKUP_OBJECT (hh_window_modif, hbox16, "hbox16");
  GLADE_HOOKUP_OBJECT (hh_window_modif, image18, "image18");
  GLADE_HOOKUP_OBJECT (hh_window_modif, label23, "label23");
  GLADE_HOOKUP_OBJECT (hh_window_modif, id_modif, "id_modif");
  GLADE_HOOKUP_OBJECT (hh_window_modif, date_exp, "date_exp");
  GLADE_HOOKUP_OBJECT (hh_window_modif, date_a_modif, "date_a_modif");
  GLADE_HOOKUP_OBJECT (hh_window_modif, quantitea, "quantitea");
  GLADE_HOOKUP_OBJECT (hh_window_modif, type_modifier, "type_modifier");
  GLADE_HOOKUP_OBJECT (hh_window_modif, nom_modifier, "nom_modifier");
  GLADE_HOOKUP_OBJECT (hh_window_modif, type_m, "type_m");
  GLADE_HOOKUP_OBJECT (hh_window_modif, label34, "label34");
  GLADE_HOOKUP_OBJECT (hh_window_modif, modif, "modif");

  return hh_window_modif;
}

GtkWidget*
create_hh_window_Rechercher (void)
{
  GtkWidget *hh_window_Rechercher;
  GtkWidget *label30;
  GtkWidget *entry2;
  GtkWidget *treeview3;
  GtkWidget *rech_valider;
  GtkWidget *alignment21;
  GtkWidget *hbox21;
  GtkWidget *image23;
  GtkWidget *label33;
  GtkWidget *id_rech;
  GtkWidget *retour_recherche;
  GtkWidget *alignment19;
  GtkWidget *hbox19;
  GtkWidget *image21;
  GtkWidget *label26;
  GtkWidget *hh_rechercher_error;

  hh_window_Rechercher = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (hh_window_Rechercher), _("RECHERCHER"));

  label30 = gtk_fixed_new ();
  gtk_widget_show (label30);
  gtk_container_add (GTK_CONTAINER (hh_window_Rechercher), label30);

  entry2 = gtk_entry_new ();
  gtk_widget_show (entry2);
  gtk_fixed_put (GTK_FIXED (label30), entry2, 288, 72);
  gtk_widget_set_size_request (entry2, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry2), 8226);

  treeview3 = gtk_tree_view_new ();
  gtk_widget_show (treeview3);
  gtk_fixed_put (GTK_FIXED (label30), treeview3, 16, 152);
  gtk_widget_set_size_request (treeview3, 824, 304);

  rech_valider = gtk_button_new ();
  gtk_widget_show (rech_valider);
  gtk_fixed_put (GTK_FIXED (label30), rech_valider, 512, 64);
  gtk_widget_set_size_request (rech_valider, 112, 40);

  alignment21 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment21);
  gtk_container_add (GTK_CONTAINER (rech_valider), alignment21);

  hbox21 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox21);
  gtk_container_add (GTK_CONTAINER (alignment21), hbox21);

  image23 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image23);
  gtk_box_pack_start (GTK_BOX (hbox21), image23, FALSE, FALSE, 0);

  label33 = gtk_label_new_with_mnemonic (_("Rechercher"));
  gtk_widget_show (label33);
  gtk_box_pack_start (GTK_BOX (hbox21), label33, FALSE, FALSE, 0);

  id_rech = gtk_label_new (_("Donner l'ID :"));
  gtk_widget_show (id_rech);
  gtk_fixed_put (GTK_FIXED (label30), id_rech, 168, 72);
  gtk_widget_set_size_request (id_rech, 120, 25);

  retour_recherche = gtk_button_new ();
  gtk_widget_show (retour_recherche);
  gtk_fixed_put (GTK_FIXED (label30), retour_recherche, 392, 528);
  gtk_widget_set_size_request (retour_recherche, 88, 32);

  alignment19 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment19);
  gtk_container_add (GTK_CONTAINER (retour_recherche), alignment19);

  hbox19 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox19);
  gtk_container_add (GTK_CONTAINER (alignment19), hbox19);

  image21 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image21);
  gtk_box_pack_start (GTK_BOX (hbox19), image21, FALSE, FALSE, 0);

  label26 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label26);
  gtk_box_pack_start (GTK_BOX (hbox19), label26, FALSE, FALSE, 0);

  hh_rechercher_error = gtk_label_new ("");
  gtk_widget_show (hh_rechercher_error);
  gtk_fixed_put (GTK_FIXED (label30), hh_rechercher_error, 288, 16);
  gtk_widget_set_size_request (hh_rechercher_error, 248, 32);

  g_signal_connect ((gpointer) treeview3, "row_activated",
                    G_CALLBACK (on_treeview3_row_activated),
                    NULL);
  g_signal_connect ((gpointer) rech_valider, "clicked",
                    G_CALLBACK (on_rech_valider_clicked),
                    NULL);
  g_signal_connect ((gpointer) retour_recherche, "clicked",
                    G_CALLBACK (on_retour_recherche_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (hh_window_Rechercher, hh_window_Rechercher, "hh_window_Rechercher");
  GLADE_HOOKUP_OBJECT (hh_window_Rechercher, label30, "label30");
  GLADE_HOOKUP_OBJECT (hh_window_Rechercher, entry2, "entry2");
  GLADE_HOOKUP_OBJECT (hh_window_Rechercher, treeview3, "treeview3");
  GLADE_HOOKUP_OBJECT (hh_window_Rechercher, rech_valider, "rech_valider");
  GLADE_HOOKUP_OBJECT (hh_window_Rechercher, alignment21, "alignment21");
  GLADE_HOOKUP_OBJECT (hh_window_Rechercher, hbox21, "hbox21");
  GLADE_HOOKUP_OBJECT (hh_window_Rechercher, image23, "image23");
  GLADE_HOOKUP_OBJECT (hh_window_Rechercher, label33, "label33");
  GLADE_HOOKUP_OBJECT (hh_window_Rechercher, id_rech, "id_rech");
  GLADE_HOOKUP_OBJECT (hh_window_Rechercher, retour_recherche, "retour_recherche");
  GLADE_HOOKUP_OBJECT (hh_window_Rechercher, alignment19, "alignment19");
  GLADE_HOOKUP_OBJECT (hh_window_Rechercher, hbox19, "hbox19");
  GLADE_HOOKUP_OBJECT (hh_window_Rechercher, image21, "image21");
  GLADE_HOOKUP_OBJECT (hh_window_Rechercher, label26, "label26");
  GLADE_HOOKUP_OBJECT (hh_window_Rechercher, hh_rechercher_error, "hh_rechercher_error");

  return hh_window_Rechercher;
}

GtkWidget*
create_hh_window_rupture (void)
{
  GtkWidget *hh_window_rupture;
  GtkWidget *fixed8;
  GtkWidget *hh_rupture;
  GtkWidget *label39;
  GtkWidget *retour_rupture;
  GtkWidget *alignment20;
  GtkWidget *hbox20;
  GtkWidget *image22;
  GtkWidget *label27;

  hh_window_rupture = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (hh_window_rupture), _("PRODUITS EN RUPTURE"));

  fixed8 = gtk_fixed_new ();
  gtk_widget_show (fixed8);
  gtk_container_add (GTK_CONTAINER (hh_window_rupture), fixed8);

  hh_rupture = gtk_tree_view_new ();
  gtk_widget_show (hh_rupture);
  gtk_fixed_put (GTK_FIXED (fixed8), hh_rupture, 24, 64);
  gtk_widget_set_size_request (hh_rupture, 720, 352);

  label39 = gtk_label_new (_("Si il y a un produit en rupture, il s'affichera ici."));
  gtk_widget_show (label39);
  gtk_fixed_put (GTK_FIXED (fixed8), label39, 144, 16);
  gtk_widget_set_size_request (label39, 472, 32);

  retour_rupture = gtk_button_new ();
  gtk_widget_show (retour_rupture);
  gtk_fixed_put (GTK_FIXED (fixed8), retour_rupture, 344, 440);
  gtk_widget_set_size_request (retour_rupture, 80, 32);

  alignment20 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment20);
  gtk_container_add (GTK_CONTAINER (retour_rupture), alignment20);

  hbox20 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox20);
  gtk_container_add (GTK_CONTAINER (alignment20), hbox20);

  image22 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image22);
  gtk_box_pack_start (GTK_BOX (hbox20), image22, FALSE, FALSE, 0);

  label27 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label27);
  gtk_box_pack_start (GTK_BOX (hbox20), label27, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) hh_rupture, "row_activated",
                    G_CALLBACK (on_hh_rupture_row_activated),
                    NULL);
  g_signal_connect ((gpointer) retour_rupture, "clicked",
                    G_CALLBACK (on_retour_rupture_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (hh_window_rupture, hh_window_rupture, "hh_window_rupture");
  GLADE_HOOKUP_OBJECT (hh_window_rupture, fixed8, "fixed8");
  GLADE_HOOKUP_OBJECT (hh_window_rupture, hh_rupture, "hh_rupture");
  GLADE_HOOKUP_OBJECT (hh_window_rupture, label39, "label39");
  GLADE_HOOKUP_OBJECT (hh_window_rupture, retour_rupture, "retour_rupture");
  GLADE_HOOKUP_OBJECT (hh_window_rupture, alignment20, "alignment20");
  GLADE_HOOKUP_OBJECT (hh_window_rupture, hbox20, "hbox20");
  GLADE_HOOKUP_OBJECT (hh_window_rupture, image22, "image22");
  GLADE_HOOKUP_OBJECT (hh_window_rupture, label27, "label27");

  return hh_window_rupture;
}

GtkWidget*
create_hh_mail (void)
{
  GtkWidget *hh_mail;
  GtkWidget *fixed9;
  GtkWidget *hh_email_cmpt;
  GtkWidget *text_mail;
  GtkWidget *hh_annuler_mail;
  GtkWidget *alignment25;
  GtkWidget *hbox25;
  GtkWidget *image27;
  GtkWidget *label42;
  GtkWidget *hh_valider_mail;
  GtkWidget *alignment26;
  GtkWidget *hbox26;
  GtkWidget *image28;
  GtkWidget *label43;
  GtkWidget *retour_mail;
  GtkWidget *alignment27;
  GtkWidget *hbox27;
  GtkWidget *image29;
  GtkWidget *label44;
  GtkWidget *text_email;

  hh_mail = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (hh_mail), _("window1"));

  fixed9 = gtk_fixed_new ();
  gtk_widget_show (fixed9);
  gtk_container_add (GTK_CONTAINER (hh_mail), fixed9);

  hh_email_cmpt = gtk_entry_new ();
  gtk_widget_show (hh_email_cmpt);
  gtk_fixed_put (GTK_FIXED (fixed9), hh_email_cmpt, 88, 96);
  gtk_widget_set_size_request (hh_email_cmpt, 296, 48);
  gtk_entry_set_invisible_char (GTK_ENTRY (hh_email_cmpt), 8226);

  text_mail = gtk_label_new (_("Donner l email :"));
  gtk_widget_show (text_mail);
  gtk_fixed_put (GTK_FIXED (fixed9), text_mail, 128, 64);
  gtk_widget_set_size_request (text_mail, 232, 32);

  hh_annuler_mail = gtk_button_new ();
  gtk_widget_show (hh_annuler_mail);
  gtk_fixed_put (GTK_FIXED (fixed9), hh_annuler_mail, 16, 232);
  gtk_widget_set_size_request (hh_annuler_mail, 120, 48);

  alignment25 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment25);
  gtk_container_add (GTK_CONTAINER (hh_annuler_mail), alignment25);

  hbox25 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox25);
  gtk_container_add (GTK_CONTAINER (alignment25), hbox25);

  image27 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image27);
  gtk_box_pack_start (GTK_BOX (hbox25), image27, FALSE, FALSE, 0);

  label42 = gtk_label_new_with_mnemonic (_("Annuler"));
  gtk_widget_show (label42);
  gtk_box_pack_start (GTK_BOX (hbox25), label42, FALSE, FALSE, 0);

  hh_valider_mail = gtk_button_new ();
  gtk_widget_show (hh_valider_mail);
  gtk_fixed_put (GTK_FIXED (fixed9), hh_valider_mail, 176, 232);
  gtk_widget_set_size_request (hh_valider_mail, 128, 48);

  alignment26 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment26);
  gtk_container_add (GTK_CONTAINER (hh_valider_mail), alignment26);

  hbox26 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox26);
  gtk_container_add (GTK_CONTAINER (alignment26), hbox26);

  image28 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image28);
  gtk_box_pack_start (GTK_BOX (hbox26), image28, FALSE, FALSE, 0);

  label43 = gtk_label_new_with_mnemonic (_("Valider"));
  gtk_widget_show (label43);
  gtk_box_pack_start (GTK_BOX (hbox26), label43, FALSE, FALSE, 0);

  retour_mail = gtk_button_new ();
  gtk_widget_show (retour_mail);
  gtk_fixed_put (GTK_FIXED (fixed9), retour_mail, 344, 232);
  gtk_widget_set_size_request (retour_mail, 112, 48);

  alignment27 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment27);
  gtk_container_add (GTK_CONTAINER (retour_mail), alignment27);

  hbox27 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox27);
  gtk_container_add (GTK_CONTAINER (alignment27), hbox27);

  image29 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image29);
  gtk_box_pack_start (GTK_BOX (hbox27), image29, FALSE, FALSE, 0);

  label44 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label44);
  gtk_box_pack_start (GTK_BOX (hbox27), label44, FALSE, FALSE, 0);

  text_email = gtk_label_new ("");
  gtk_widget_show (text_email);
  gtk_fixed_put (GTK_FIXED (fixed9), text_email, 104, 320);
  gtk_widget_set_size_request (text_email, 256, 40);

  g_signal_connect ((gpointer) hh_annuler_mail, "clicked",
                    G_CALLBACK (on_hh_annuler_mail_clicked),
                    NULL);
  g_signal_connect ((gpointer) hh_valider_mail, "clicked",
                    G_CALLBACK (on_hh_valider_mail_clicked),
                    NULL);
  g_signal_connect ((gpointer) retour_mail, "clicked",
                    G_CALLBACK (on_retour_mail_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (hh_mail, hh_mail, "hh_mail");
  GLADE_HOOKUP_OBJECT (hh_mail, fixed9, "fixed9");
  GLADE_HOOKUP_OBJECT (hh_mail, hh_email_cmpt, "hh_email_cmpt");
  GLADE_HOOKUP_OBJECT (hh_mail, text_mail, "text_mail");
  GLADE_HOOKUP_OBJECT (hh_mail, hh_annuler_mail, "hh_annuler_mail");
  GLADE_HOOKUP_OBJECT (hh_mail, alignment25, "alignment25");
  GLADE_HOOKUP_OBJECT (hh_mail, hbox25, "hbox25");
  GLADE_HOOKUP_OBJECT (hh_mail, image27, "image27");
  GLADE_HOOKUP_OBJECT (hh_mail, label42, "label42");
  GLADE_HOOKUP_OBJECT (hh_mail, hh_valider_mail, "hh_valider_mail");
  GLADE_HOOKUP_OBJECT (hh_mail, alignment26, "alignment26");
  GLADE_HOOKUP_OBJECT (hh_mail, hbox26, "hbox26");
  GLADE_HOOKUP_OBJECT (hh_mail, image28, "image28");
  GLADE_HOOKUP_OBJECT (hh_mail, label43, "label43");
  GLADE_HOOKUP_OBJECT (hh_mail, retour_mail, "retour_mail");
  GLADE_HOOKUP_OBJECT (hh_mail, alignment27, "alignment27");
  GLADE_HOOKUP_OBJECT (hh_mail, hbox27, "hbox27");
  GLADE_HOOKUP_OBJECT (hh_mail, image29, "image29");
  GLADE_HOOKUP_OBJECT (hh_mail, label44, "label44");
  GLADE_HOOKUP_OBJECT (hh_mail, text_email, "text_email");

  return hh_mail;
}

