/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

int
main (int argc, char *argv[])
{
  GtkWidget *hh_window_produits;
  GtkWidget *hh_window_supp;
  GtkWidget *hh_window_ajout;
  GtkWidget *hh_window_modif;
  GtkWidget *hh_window_Rechercher;
  GtkWidget *hh_window_rupture;

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */

  hh_window_produits = create_hh_window_produits ();
  gtk_widget_show (hh_window_produits);
  /*hh_window_supp = create_hh_window_supp ();
  gtk_widget_show (hh_window_supp);
  hh_window_ajout = create_hh_window_ajout ();
  gtk_widget_show (hh_window_ajout);
  hh_window_modif = create_hh_window_modif ();
  gtk_widget_show (hh_window_modif);
  hh_window_Rechercher = create_hh_window_Rechercher ();
  gtk_widget_show (hh_window_Rechercher);
  hh_window_rupture = create_hh_window_rupture ();
  gtk_widget_show (hh_window_rupture);*/

  gtk_main ();
  return 0;
}

